=== Occupant-Oriented-Demand-Response/Conrol-Results/data/config/heat_pump_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Heat pump config",
    "description": "This document records the details of a heat pump config.",
    "$ref": "#/$defs/schema",
    "$defs": {
        "schema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "outside_air_temperature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "electrical_power_consumption_max": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "coefficient_of_performance_nenn": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            },
            "required": [
                "coefficient_of_performance_nenn",
                "electrical_power_consumption_max",
                "name",
                "outside_air_temperature"
            ]
        }
    }
}

=== Occupant-Oriented-Demand-Response/Conrol-Results/data/config/heat_pump_config.json
{
    "name": "AERO SLM 3-11 HGL",
    "outside_air_temperature": [
        -10,
        -7,
        2,
        7,
        10,
        12,
        15,
        20
    ],
    "electrical_power_consumption_max": [
        4200,
        4390,
        4830,
        4620,
        4400,
        4410,
        4000,
        3320
    ],
    "coefficient_of_performance_nenn": [
        1.98,
        2.2,
        2.71,
        3.1,
        3.34,
        3.55,
        3.89,
        4.26
    ]
}
